version: 1.0.{build}
image: Visual Studio 2019
configuration: Release

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

cache:
- msbuild\vcpkg\installed -> msbuild\packages.bat
- C:\Users\appveyor\clcache -> .appveyor.yml, msbuild\**

- ps: |
      cd c:\tools\vcpkg
      $env:GIT_REDIRECT_STDERR = '2>&1' # git is writing non-errors to STDERR when doing git pull. Send to STDOUT instead.
      git pull origin master
      git checkout $env:VCPKG_COMMIT_ID
      .\bootstrap-vcpkg.bat
      cd "$env:APPVEYOR_BUILD_FOLDER"
      cd msbuild
      packages.bat
      cd "$env:APPVEYOR_BUILD_FOLDER"
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
before_build:
- ps: >-
    nuget install Tools.InnoSetup

build:
  parallel: true                  # enable MSBuild parallel builds
  project: msbuild\domoticz.sln   # path to Visual Studio solution or project
  verbosity: minimal

after_build:
- cmd: >-
    cp appversion.h version_windows_x86.h
    
    cp History.txt history_windows_x86.txt
    
    Tools.InnoSetup.6.0.3\tools\ISCC msbuild\WindowsInstaller\DomoticzSetup.iss
    
    msbuild msbuild\package.proj

artifacts:
- path: domoticz_windows_x86.zip
- path: version_windows_x86.h
- path: history_windows_x86.txt
- path: History.txt

test: off

deploy:
- provider: FTP
  protocol: sftp
  host: $(FTP_HOST)
  username: $(FTP_USER)
  password: $(FTP_PASSWORD)
  folder: beta
  on:
    APPVEYOR_REPO_NAME: domoticz/domoticz
    APPVEYOR_REPO_BRANCH: development

